# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - "nightly"
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    - 'if [[ $GROUP != js* ]]; then COVERAGE=""; fi'
install:
    - pip install "setuptools>=18.5"
    - pip install -f travis-wheels/wheelhouse -e file://$PWD#egg=ipython[test]
    - pip install codecov
script:
    - python -c 'import re'
    - cd /tmp && iptest --coverage xml && cd -
after_success:
    - cp /tmp/ipy_coverage.xml ./
    - cp /tmp/.coverage ./
    - codecov

matrix:
    allow_failures:
        - python: nightly
