# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - "nightly"
sudo: false
install:
    - pip install "setuptools>=18.5"
    - pip install -f travis-wheels/wheelhouse -e file://$PWD#egg=ipython[test]
    - pip install codecov
script:
    - python -m IPython --quick --colors=NoColor --no-term-title --no-banner --autocall=0 foo.py
    - cd /tmp && iptest --coverage xml && cd -
after_success:
    - cp /tmp/ipy_coverage.xml ./
    - cp /tmp/.coverage ./

matrix:
    allow_failures:
        - python: nightly
